### PR TITLE
Fix go vet error 'composite literal uses unkeyed fields' in generated code

### LINKED ISSUE #435: Code generated by apiregister-gen fails go vet
The versioned `api.register.go` generated by `apiregister-gen` (either `tip` and `v1.15.alpha.1`) fails go vet check with the following violations:

```
$ go vet --all $(go list ./...)
# sigs.k8s.io/apiserver-builder-alpha/example/basic/pkg/apis/innsmouth/v1
pkg/apis/innsmouth/v1/zz_generated.api.register.go:45:5: sigs.k8s.io/apiserver-builder-alpha/example/basic/pkg/apis/innsmouth.DeepOneStatusStrategy composite literal uses unkeyed fields
# sigs.k8s.io/apiserver-builder-alpha/example/basic/pkg/apis/kingsport/v1
pkg/apis/kingsport/v1/zz_generated.api.register.go:45:5: sigs.k8s.io/apiserver-builder-alpha/example/basic/pkg/apis/kingsport.FestivalStatusStrategy composite literal uses unkeyed fields
# sigs.k8s.io/apiserver-builder-alpha/example/basic/pkg/apis/miskatonic/v1beta1
pkg/apis/miskatonic/v1beta1/zz_generated.api.register.go:57:5: sigs.k8s.io/apiserver-builder-alpha/example/basic/pkg/apis/miskatonic.UniversityStatusStrategy composite literal uses unkeyed fields
pkg/apis/miskatonic/v1beta1/zz_generated.api.register.go:63:13: sigs.k8s.io/apiserver-builder-alpha/example/basic/pkg/apis/miskatonic.UniversityCampusREST composite literal uses unkeyed fields
# sigs.k8s.io/apiserver-builder-alpha/example/basic/pkg/apis/olympus/v1beta1
pkg/apis/olympus/v1beta1/zz_generated.api.register.go:45:5: sigs.k8s.io/apiserver-builder-alpha/example/basic/pkg/apis/olympus.PoseidonStatusStrategy composite literal uses unkeyed fields
```

The registry code is typically generated in the versioned apis package, therefore, it cannot be ignored during check like the client packages inside `clientset_generated` directory and should be able to pass checks like `go vet` in most cases.

### PR DESCRIPTION
**Pull request by aylei**
close #435 

Also, `go vet` check is added in the test.

Signed-off-by: Aylei <rayingecho@gmail.com>

### CODE REVIEW

File: test/Makefile [hunk 1]
```diff
@@ -18,10 +18,13 @@ all: test
 
 NON_INTERACTIVE_FLAG=--skip-resource=false --skip-controller=false --skip-admission-controller=false
 
-test: build
+test: build check
 	go test ./pkg/...
 	bash -c "find pkg/apis/ -name apiserver.local.config | xargs rm -rf"
 
+check: build
+	go vet $$(go list ./... | grep -vE "_generated" | grep -vE "plugin/admission")
```
Comment (aylei) [inline test/Makefile]: Some go files under the `plugin/admission` cannot pass go vet check, workaround it for now.
```
go vet $(go list ./... | grep -vE "_generated")
# sigs.k8s.io/apiserver-builder-alpha/test/plugin/admission/snapshot
plugin/admission/snapshot/admission.go:54:58: undefined: "sigs.k8s.io/apiserver-builder-alpha/test/vendor/k8s.io/apiserver/pkg/admission".ObjectInterface
plugin/admission/snapshot/admission.go:58:61: undefined: "sigs.k8s.io/apiserver-builder-alpha/test/vendor/k8s.io/apiserver/pkg/admission".ObjectInterface
# sigs.k8s.io/apiserver-builder-alpha/test/plugin/admission/snapshotclaim
plugin/admission/snapshotclaim/admission.go:54:63: undefined: "sigs.k8s.io/apiserver-builder-alpha/test/vendor/k8s.io/apiserver/pkg/admission".ObjectInterface
plugin/admission/snapshotclaim/admission.go:58:66: undefined: "sigs.k8s.io/apiserver-builder-alpha/test/vendor/k8s.io/apiserver/pkg/admission".ObjectInterface
# sigs.k8s.io/apiserver-builder-alpha/test/plugin/admission/volume
plugin/admission/volume/admission.go:54:56: undefined: "sigs.k8s.io/apiserver-builder-alpha/test/vendor/k8s.io/apiserver/pkg/admission".ObjectInterface
plugin/admission/volume/admission.go:58:59: undefined: "sigs.k8s.io/apiserver-builder-alpha/test/vendor/k8s.io/apiserver/pkg/admission".ObjectInterface
# sigs.k8s.io/apiserver-builder-alpha/test/plugin/admission/volumeclaim
plugin/admission/volumeclaim/admission.go:54:61: undefined: "sigs.k8s.io/apiserver-builder-alpha/test/vendor/k8s.io/apiserver/pkg/admission".ObjectInterface
plugin/admission/volumeclaim/admission.go:58:64: undefined: "sigs.k8s.io/apiserver-builder-alpha/test/vendor/k8s.io/apiserver/pkg/admission".ObjectInterface
```
Looks like that these cannot even compile, the test succeed formerly because the builded binaries does not involve these go files.

**Comment by aylei** [comment]
/assign yue9944882
Could you please take a look?

File: test/Makefile (hunk 1 above)
Comment (aylei) [reply test/Makefile]: I believe it is introduced by the dependency bump, now that we have upgraded the kubernetes dependencies to `1.16`, apiserver-boot should also be updated: https://github.com/kubernetes-sigs/apiserver-builder-alpha/blob/master/cmd/apiserver-boot/boot/create/resource.go#L509

 Tracked by: https://github.com/kubernetes-sigs/apiserver-builder-alpha/issues/437

Comment (yue9944882) [reply test/Makefile]: thanks, i fixed compile issue by https://github.com/kubernetes-sigs/apiserver-builder-alpha/pull/438. rebase onto that and vetting admission packages should work now

Comment (yue9944882) [inline test/Makefile]: sanitizing all _generated files is probably overkilling, i suggest:

```suggestion
	go vet $$(go list ./... | grep -vE '(clientset|listers|informers)_generated'
```

**Comment by aylei** [comment]
@yue9944882 Seems like that #438 did not fix the problem thoroughly, I added a fix and squashed the commits, could you please take a look again?

File: cmd/apiserver-boot/boot/create/resource.go [hunk 2]
```diff
@@ -502,11 +503,11 @@ func (p *{{ lower .Kind }}Plugin) ValidateInitialization() error {
 	return nil
 }
 
-func (p *{{ lower .Kind }}Plugin) Admit(ctx context.Context, a admission.Attributes, o admission.ObjectInterface) error {
+func (p *{{ lower .Kind }}Plugin) Admit(ctx context.Context, a admission.Attributes, o admission.ObjectInterfaces) error {
 	return nil
 }
 
-func (p *{{ lower .Kind }}Plugin) Validate(ctx context.Context, a admission.Attributes, o admission.ObjectInterface) error {
+func (p *{{ lower .Kind }}Plugin) Validate(ctx context.Context, a admission.Attributes, o admission.ObjectInterfaces) error {
```
Comment (yue9944882) [inline cmd/apiserver-boot/boot/create/resource.go]: dang, oversight. LGTM now, but can you drop the non-ff merge commit from the pull?

**Comment by yue9944882** [comment]
can you rebase? the bot's complaining as well

**Comment by aylei** [comment]
@yue9944882 done, PTAL
